[build]
  publish = "dist"
  command = "npm install --include=dev && npx vite build"

[dev]
  command = "npm run dev"

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  NODE_ENV = "production"
